import type { AcademicCrudConfig } from "@/app/types/academicTypes";
import type { ModalFieldOption } from "@/app/types/components/modalTypes";

const gradeLevelOptions: ModalFieldOption[] = [1, 2, 3, 4, 5, 6].map((gradeLevel) => ({
  label: `Grade ${gradeLevel}`,
  value: String(gradeLevel),
}));

const schoolYearStatusOptions: ModalFieldOption[] = [
  { label: "Active", value: "true" },
  { label: "Inactive", value: "false" },
];

const sf10StatusOptions: ModalFieldOption[] = [
  { label: "Draft", value: "draft" },
  { label: "For Verification", value: "for_verification" },
  { label: "Verified", value: "verified" },
  { label: "Certified", value: "certified" },
  { label: "Released", value: "released" },
];

const enrollmentStatusOptions: ModalFieldOption[] = [
  { label: "Enrolled", value: "enrolled" },
  { label: "Transferred Out", value: "transferred_out" },
  { label: "Dropped", value: "dropped" },
  { label: "Completed", value: "completed" },
];

const admissionTypeOptions: ModalFieldOption[] = [
  { label: "Continuing", value: "continuing" },
  { label: "New Learner", value: "new_learner" },
  { label: "Transferee In", value: "transferee_in" },
  { label: "Balik-Aral", value: "balik_aral" },
  { label: "Returning", value: "returning" },
];

const completionStatusOptions: ModalFieldOption[] = [
  { label: "Not Applicable", value: "not_applicable" },
  { label: "Promoted", value: "promoted" },
  { label: "Retained", value: "retained" },
];

const credentialTypeOptions: ModalFieldOption[] = [
  { label: "Kinder Progress Report", value: "kinder_progress_report" },
  { label: "PEPT", value: "pept" },
  { label: "Other", value: "other" },
];

export const academicPageConfigs = {
  schoolYears: {
    entity: "school-years",
    title: "School Years",
    recordLabel: "School Year",
    breadcrumb: "Home > Settings > School Years",
    description: "Manage school year periods used in SF10 records and sections.",
    addLabel: "Add School Year",
    modalSize: "sm",
    modalColumns: 1,
    modalGridClassName: "grid-cols-1 gap-y-4",
    fields: [
      {
        name: "name",
        label: "School Year",
        inputType: "school-year-range",
        required: true,
        placeholder: "2026-2027",
      },
      {
        name: "startDate",
        label: "Date Range",
        valueType: "date",
        inputType: "date-range",
        rangeEndName: "endDate",
      },
      { name: "endDate", label: "End Date", valueType: "date", inputType: "date", form: false },
      {
        name: "isActive",
        label: "Status",
        valueType: "boolean",
        inputType: "radio-group",
        defaultValue: "false",
        options: schoolYearStatusOptions,
      },
    ],
  },
  teachers: {
    entity: "teachers",
    title: "Teachers / Advisers",
    recordLabel: "Teacher / Adviser",
    breadcrumb: "Home > Settings > Teachers",
    description: "Manage advisers and teachers used in scholastic records.",
    addLabel: "Add Teacher / Adviser",
    modalSize: "md",
    modalColumns: 1,
    modalGridClassName: "grid-cols-1 gap-y-4",
    fields: [
      {
        name: "userId",
        label: "Teacher / Adviser User",
        valueType: "number",
        inputType: "lookup",
        lookupSource: "teaching-users",
        placeholder: "Search user by name, position, or email",
        required: true,
        table: false,
      },
      { name: "teacherName", label: "Name", form: false },
      { name: "position", label: "Position", form: false },
      { name: "email", label: "Email", form: false },
    ],
  },
  sections: {
    entity: "sections",
    title: "Sections",
    recordLabel: "Section",
    breadcrumb: "Home > Settings > Sections",
    description: "Manage grade level sections and adviser assignments.",
    addLabel: "Add Section",
    modalSize: "lg",
    modalColumns: 2,
    modalGridClassName: "grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-4",
    fields: [
      {
        name: "schoolYearId",
        label: "School Year",
        valueType: "number",
        inputType: "select",
        lookupSource: "school-years",
        placeholder: "Select school year",
        required: true,
        table: false,
      },
      { name: "schoolYearName", label: "School Year", form: false },
      {
        name: "gradeLevel",
        label: "Grade Level",
        valueType: "number",
        defaultValue: "1",
        inputType: "select",
        options: gradeLevelOptions,
        required: true,
      },
      { name: "sectionName", label: "Section Name", required: true, placeholder: "Mabini" },
      {
        name: "adviserId",
        label: "Adviser",
        valueType: "number",
        inputType: "lookup",
        lookupSource: "teachers",
        placeholder: "Search adviser by name, position, or email",
        table: false,
      },
      { name: "adviserName", label: "Adviser", form: false },
      {
        name: "capacityLimit",
        label: "Student Limit",
        valueType: "number",
        placeholder: "40",
      },
    ],
  },
  enrollments: {
    entity: "enrollments",
    title: "Enrollments",
    recordLabel: "Enrollment",
    breadcrumb: "Home > Academic > Enrollments",
    description: "Assign students to school years, grade levels, and sections.",
    addLabel: "Add Enrollment",
    modalSize: "lg",
    modalColumns: 2,
    modalGridClassName: "grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-4",
    showUpdatedColumn: false,
    fields: [
      {
        name: "studentId",
        label: "Student",
        valueType: "number",
        inputType: "lookup",
        lookupSource: "students",
        placeholder: "Search student by name or LRN",
        required: true,
        table: false,
      },
      { name: "studentName", label: "Student", form: false },
      { name: "lrn", label: "LRN", form: false, table: false },
      { name: "profilePicture", label: "Student Image", form: false, table: false },
      {
        name: "schoolYearId",
        label: "School Year",
        valueType: "number",
        inputType: "select",
        lookupSource: "school-years",
        placeholder: "Select school year",
        required: true,
        table: false,
      },
      { name: "schoolYearName", label: "School Year", form: false, table: false },
      {
        name: "sectionId",
        label: "Section",
        valueType: "number",
        inputType: "lookup",
        lookupSource: "sections",
        placeholder: "Search section by school year, grade, or name",
        required: true,
        table: false,
      },
      { name: "sectionName", label: "Section", form: false, table: false },
      { name: "gradeSection", label: "Grade & Section", form: false },
      {
        name: "admissionType",
        label: "Admission Type",
        inputType: "select",
        options: admissionTypeOptions,
        defaultValue: "continuing",
      },
      {
        name: "status",
        label: "Enrollment Status",
        inputType: "select",
        options: enrollmentStatusOptions,
        defaultValue: "enrolled",
      },
      {
        name: "enrollmentDate",
        label: "Enrollment Date",
        valueType: "date",
        inputType: "date",
      },
      {
        name: "completionStatus",
        label: "Completion",
        inputType: "select",
        options: completionStatusOptions,
        defaultValue: "not_applicable",
        table: false,
      },
      {
        name: "previousSchoolName",
        label: "Previous School Name",
        placeholder: "Previous school",
        visibleWhen: { name: "admissionType", value: "transferee_in" },
        table: false,
      },
      {
        name: "previousSchoolIdText",
        label: "Previous School ID",
        placeholder: "School ID",
        visibleWhen: { name: "admissionType", value: "transferee_in" },
        table: false,
      },
      {
        name: "previousGradeLevel",
        label: "Previous Grade Level",
        valueType: "number",
        inputType: "select",
        options: gradeLevelOptions,
        placeholder: "Select previous grade",
        visibleWhen: { name: "admissionType", value: "transferee_in" },
        table: false,
      },
      {
        name: "transferInDate",
        label: "Transfer In Date",
        valueType: "date",
        inputType: "date",
        visibleWhen: { name: "admissionType", value: "transferee_in" },
        table: false,
      },
      {
        name: "documentsSubmitted",
        label: "Documents Submitted",
        inputType: "textarea",
        placeholder: "SF10, birth certificate, or other submitted records",
        visibleWhen: { name: "admissionType", value: "transferee_in" },
        table: false,
        colSpan: 2,
      },
      { name: "capacityLimit", label: "Section Limit", form: false, table: false },
      { name: "adviserName", label: "Adviser", form: false, table: false },
      { name: "remarks", label: "Remarks", inputType: "textarea", colSpan: 2, table: false },
    ],
  },
  sf10Records: {
    entity: "sf10-records",
    title: "SF10 Records",
    breadcrumb: "Home > Students > SF10 Records",
    description: "Manage each learner's SF10 master record status and certification workflow.",
    addLabel: "Add SF10 Record",
    fields: [
      { name: "studentId", label: "Student ID", valueType: "number", required: true },
      { name: "schoolId", label: "School ID", valueType: "number" },
      {
        name: "status",
        label: "Status",
        inputType: "select",
        options: sf10StatusOptions,
        defaultValue: "draft",
      },
      { name: "remarks", label: "Remarks", inputType: "textarea", colSpan: 2 },
      { name: "createdBy", label: "Created By User ID", valueType: "number", table: false },
      { name: "verifiedBy", label: "Verified By User ID", valueType: "number", table: false },
      { name: "certifiedBy", label: "Certified By User ID", valueType: "number", table: false },
      { name: "completedAt", label: "Completed At", valueType: "datetime", placeholder: "2026-05-30 10:30:00" },
    ],
  },
  scholasticRecords: {
    entity: "scholastic-records",
    title: "Scholastic Records",
    breadcrumb: "Home > Settings > Scholastic Records",
    description: "Manage per-grade SF10 scholastic history connected to students, sections, and advisers.",
    addLabel: "Add Scholastic Record",
    fields: [
      { name: "sf10RecordId", label: "SF10 Record ID", valueType: "number", required: true },
      { name: "studentId", label: "Student ID", valueType: "number", required: true },
      { name: "schoolId", label: "School ID", valueType: "number", table: false },
      { name: "schoolYearId", label: "School Year ID", valueType: "number", required: true },
      { name: "sectionId", label: "Section ID", valueType: "number" },
      { name: "adviserId", label: "Adviser ID", valueType: "number" },
      {
        name: "gradeLevel",
        label: "Grade Level",
        valueType: "number",
        inputType: "select",
        options: gradeLevelOptions,
        required: true,
      },
      { name: "sectionName", label: "Section Name" },
      { name: "district", label: "District", table: false },
      { name: "division", label: "Division", table: false },
      { name: "region", label: "Region", table: false },
      { name: "generalAverage", label: "General Average", valueType: "number" },
      { name: "finalRemarks", label: "Final Remarks" },
    ],
  },
  grades: {
    entity: "grades",
    title: "Grades",
    breadcrumb: "Home > Students > Grades",
    description: "Encode quarterly grades, final rating, and remarks per subject.",
    addLabel: "Add Grade",
    fields: [
      { name: "scholasticRecordId", label: "Scholastic Record ID", valueType: "number", required: true },
      { name: "subjectId", label: "Subject ID", valueType: "number", required: true },
      { name: "quarter1", label: "Quarter 1", valueType: "number" },
      { name: "quarter2", label: "Quarter 2", valueType: "number" },
      { name: "quarter3", label: "Quarter 3", valueType: "number" },
      { name: "quarter4", label: "Quarter 4", valueType: "number" },
      { name: "finalRating", label: "Final Rating", valueType: "number" },
      { name: "remarks", label: "Remarks" },
    ],
  },
  remedialClasses: {
    entity: "remedial-classes",
    title: "Remedial Classes",
    breadcrumb: "Home > Settings > Remedial Classes",
    description: "Track remedial classes, recomputed final grade, and remarks.",
    addLabel: "Add Remedial Class",
    fields: [
      { name: "scholasticRecordId", label: "Scholastic Record ID", valueType: "number", required: true },
      { name: "subjectId", label: "Subject ID", valueType: "number", required: true },
      { name: "dateFrom", label: "Date From", valueType: "date", inputType: "date" },
      { name: "dateTo", label: "Date To", valueType: "date", inputType: "date" },
      { name: "finalRating", label: "Final Rating", valueType: "number" },
      { name: "remedialClassMark", label: "Remedial Mark", valueType: "number" },
      { name: "recomputedFinalGrade", label: "Recomputed Grade", valueType: "number" },
      { name: "remarks", label: "Remarks" },
    ],
  },
  eligibilityRecords: {
    entity: "eligibility-records",
    title: "Eligibility Records",
    breadcrumb: "Home > Settings > Eligibility Records",
    description: "Capture learner eligibility, PEPT, and admission credential details.",
    addLabel: "Add Eligibility Record",
    fields: [
      { name: "studentId", label: "Student ID", valueType: "number", required: true },
      { name: "sf10RecordId", label: "SF10 Record ID", valueType: "number" },
      {
        name: "credentialType",
        label: "Credential Type",
        inputType: "select",
        options: credentialTypeOptions,
        required: true,
      },
      { name: "schoolName", label: "School Name" },
      { name: "schoolIdText", label: "School ID Text" },
      { name: "schoolAddress", label: "School Address", inputType: "textarea", colSpan: 2 },
      { name: "peptRating", label: "PEPT Rating", valueType: "number" },
      { name: "examDate", label: "Exam Date", valueType: "date", inputType: "date" },
      { name: "testingCenter", label: "Testing Center" },
      { name: "otherCredential", label: "Other Credential" },
      { name: "remarks", label: "Remarks", inputType: "textarea", colSpan: 2 },
    ],
  },
  certifications: {
    entity: "certifications",
    title: "Certifications",
    breadcrumb: "Home > Settings > Certifications",
    description: "Manage SF10 certification details for transfer or promotion records.",
    addLabel: "Add Certification",
    fields: [
      { name: "sf10RecordId", label: "SF10 Record ID", valueType: "number", required: true },
      { name: "studentId", label: "Student ID", valueType: "number", required: true },
      {
        name: "eligibleForGrade",
        label: "Eligible For Grade",
        valueType: "number",
        inputType: "select",
        options: gradeLevelOptions,
      },
      { name: "schoolName", label: "School Name" },
      { name: "schoolIdText", label: "School ID Text" },
      { name: "division", label: "Division" },
      { name: "lastSchoolYearAttended", label: "Last School Year Attended", placeholder: "2025-2026" },
      { name: "principalName", label: "Principal Name" },
      { name: "certificationDate", label: "Certification Date", valueType: "date", inputType: "date" },
    ],
  },
} satisfies Record<string, AcademicCrudConfig>;
