import type { AdminThemeSettings, ThemePresetOption } from "@/app/types/themeTypes";

const baseTheme = {
  foreground: "#212529",
  card: "#ffffff",
  muted: "#6c757d",
  border: "#dee2e6",
  accent: "#d7ebf7",
  boxedLayout: false,
  compactMode: false,
  hideFooter: false,
  defaultSidebarCollapsed: false,
};

export const themePresetOptions: ThemePresetOption[] = [
  {
    name: "blue",
    label: "Blue",
    settings: {
      preset: "blue",
      background: "#ecf0f5",
      primary: "#3c8dbc",
      primaryStrong: "#367fa9",
      topbarForeground: "#ffffff",
      sidebar: "#343a40",
      sidebarForeground: "#c2c7d0",
      sidebarTitle: "#ffffff",
      sidebarHover: "#494e53",
      sidebarSection: "#1a2226",
      ...baseTheme,
    },
  },
  {
    name: "black",
    label: "Black",
    settings: {
      preset: "black",
      background: "#f4f6f9",
      primary: "#111827",
      primaryStrong: "#030712",
      topbarForeground: "#ffffff",
      sidebar: "#111827",
      sidebarForeground: "#d1d5db",
      sidebarTitle: "#ffffff",
      sidebarHover: "#1f2937",
      sidebarSection: "#0b1120",
      ...baseTheme,
    },
  },
  {
    name: "purple",
    label: "Purple",
    settings: {
      preset: "purple",
      background: "#eff1f7",
      primary: "#605ca8",
      primaryStrong: "#555299",
      topbarForeground: "#ffffff",
      sidebar: "#272c30",
      sidebarForeground: "#c9ced6",
      sidebarTitle: "#ffffff",
      sidebarHover: "#343a40",
      sidebarSection: "#1f2428",
      ...baseTheme,
    },
  },
  {
    name: "green",
    label: "Green",
    settings: {
      preset: "green",
      background: "#edf5f0",
      primary: "#00a65a",
      primaryStrong: "#008d4c",
      topbarForeground: "#ffffff",
      sidebar: "#243036",
      sidebarForeground: "#c8d1d3",
      sidebarTitle: "#ffffff",
      sidebarHover: "#314047",
      sidebarSection: "#182226",
      ...baseTheme,
    },
  },
  {
    name: "red",
    label: "Red",
    settings: {
      preset: "red",
      background: "#f7f0ef",
      primary: "#dd4b39",
      primaryStrong: "#d73925",
      topbarForeground: "#ffffff",
      sidebar: "#2b2f33",
      sidebarForeground: "#ced4da",
      sidebarTitle: "#ffffff",
      sidebarHover: "#3a3f44",
      sidebarSection: "#1e2226",
      ...baseTheme,
    },
  },
  {
    name: "yellow",
    label: "Yellow",
    settings: {
      preset: "yellow",
      background: "#faf7ef",
      primary: "#f39c12",
      primaryStrong: "#e08e0b",
      topbarForeground: "#1f2937",
      sidebar: "#2b2f33",
      sidebarForeground: "#d8dee4",
      sidebarTitle: "#ffffff",
      sidebarHover: "#3b4045",
      sidebarSection: "#1e2226",
      ...baseTheme,
    },
  },
  {
    name: "blue-light",
    label: "Blue Light",
    settings: {
      preset: "blue-light",
      background: "#f5f7fb",
      primary: "#3c8dbc",
      primaryStrong: "#367fa9",
      topbarForeground: "#ffffff",
      sidebar: "#f7f9fb",
      sidebarForeground: "#52606d",
      sidebarTitle: "#1f2937",
      sidebarHover: "#e7eef4",
      sidebarSection: "#e2e8f0",
      ...baseTheme,
    },
  },
  {
    name: "black-light",
    label: "Black Light",
    settings: {
      preset: "black-light",
      background: "#f4f5f7",
      primary: "#111827",
      primaryStrong: "#030712",
      topbarForeground: "#ffffff",
      sidebar: "#f8fafc",
      sidebarForeground: "#475569",
      sidebarTitle: "#0f172a",
      sidebarHover: "#e2e8f0",
      sidebarSection: "#dbe3ec",
      ...baseTheme,
    },
  },
];

export const defaultThemeSettings: AdminThemeSettings = themePresetOptions[0].settings;
